#pragma once

#if defined(WIN32) || defined(_MSC_VER)

#if defined(ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS)
#define ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS_API __declspec(dllexport)
#else
#define ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS_API __declspec(dllimport)
#endif  // defined(ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS)

#else  // defined(WIN32)
#if defined(ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS)
#define ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS_API __attribute__((visibility("default")))
#else
#define ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS_API
#endif  // defined(ANDROIDMEDIAAUDIOCOMMONTYPESV2NDK_EXPORTS)
#endif

#ifdef _WIN32
#ifdef interface
#undef interface
#endif
#endif
