#pragma once

#if defined(WIN32) || defined(_MSC_VER)

#if defined(ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_EXPORTS_IMPL)
#define ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_API __declspec(dllexport)
#else
#define ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_API __declspec(dllimport)
#endif  // defined(ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_EXPORTS_IMPL)

#else  // defined(WIN32)
#if defined(ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_EXPORTS_IMPL)
#define ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_API __attribute__((visibility("default")))
#else
#define ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_API
#endif  // defined(ANDROIDHARDWAREBLUETOOTHSOCKETV1NDK_EXPORTS_IMPL)
#endif

#ifdef _WIN32
#ifdef interface
#undef interface
#endif
#endif

