#pragma once

#if defined(WIN32) || defined(_MSC_VER)

#if defined(ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_EXPORTS)
#define ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_API __declspec(dllexport)
#else
#define ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_API __declspec(dllimport)
#endif  // defined(ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_EXPORTS)

#else  // defined(WIN32)
#if defined(ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_EXPORTS)
#define ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_API __attribute__((visibility("default")))
#else
#define ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_API
#endif  // defined(ANDROIDHARDWAREBLUETOOTHRANGINGV1NDK_EXPORTS)
#endif

#ifdef _WIN32
#ifdef interface
#undef interface
#endif
#endif
